### ISSUE TITLE
Cara Install ?

### ISSUE THREAD

**Issue by X451Sec** [mazipan/baca-quran.id#227]
Hallo Maz Ipan!
Gimana Yaa Cara Install [Quran Offline](https://github.com/mazipan/quran-offline/) 

Soalnya Saya Masih Bingung, karena banyak banget struktur foldernya.
Terlebih Saya tidak paham apa" tentang vue js / nuxt js(* Maaf kurang tau namanya 😀) .

**Comment by mazipan** [comment]
Sudah ada di readme kok mas @X451Sec
