### ISSUE TITLE
Overlapping sidebar

### ISSUE THREAD

**Issue by stackpan** [mazipan/baca-quran.id#275]
## Description

The sidebars is overlap both on widescreen view and mobile view

![Widescreen - firefox](https://github.com/mazipan/baca-quran.id/assets/55195033/c9b3f3c2-967d-4e1f-b928-77dc9efb0b88)

![Mobile screen - firefox](https://github.com/mazipan/baca-quran.id/assets/55195033/34431e6b-42de-4231-abd7-b2764edefd3b)

I've tested it on others browser too (Edge and Chrome) and the result is same

![Edge](https://github.com/mazipan/baca-quran.id/assets/55195033/f7d932c0-6dbf-42ef-a2a3-0e2d672e2af4)

![Chrome](https://github.com/mazipan/baca-quran.id/assets/55195033/4af4e17b-f8aa-4378-9222-e0b4d5c96a1d)

And also in real mobile device browser
![Chrome - Android](https://github.com/mazipan/baca-quran.id/assets/55195033/109d24b3-18d2-4910-b443-7ed165bbf018)

## Additional Information

Tested browsers:
- Mozilla Firefox 116.0.3 (64-bit) for Linux
- Microsoft Edge 116.0.1938.62 (64-bit) for Linux
- Google Chrome 116.0.5845.110 (64-bit) for Linux
- Google Chrome 116.0.1938.62 for Android

**Comment by mazipan** [comment]
<img width="656" alt="Screenshot 2023-09-04 at 10 53 20" src="https://github.com/mazipan/baca-quran.id/assets/7221389/14b74af3-0b47-425a-8a49-d5fe174e1ac5">

Found some `null` and `undefined` classes, this is due to the initial storage for theme is not exist
